targets:
  $default:
    sources:
      - lib/lizorkin/graphql/*.graphql
      - $package$
      - lib/$lib$
    builders:
      gql_build|schema_builder:
        enabled: true
      gql_build|ast_builder:
        enabled: true
      gql_build|data_builder:
        enabled: true
        options:
          schema: ppldo_flutter_test_app|lib/lizorkin/graphql/schema.graphql