name: ppldo_flutter_test_app
description: Test application for ppldonet.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview:
    git:
      url: git://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: master
  http: ^0.12.2
  connectivity: ^2.0.2
  provider: ^4.3.2+2
  uni_links: ^0.4.0
  url_launcher:
    git:
      url: git://github.com/ppldo/url_launcher.git
      ref: main
  contacts_service: ^0.4.6
  permission_handler: ^5.0.1+1
  firebase_messaging: ^8.0.0-dev.11
  firebase_core: ^0.5.3
  clipboard: ^0.1.2+8
  sentry_flutter: ^4.0.0
  stream_transform: ^1.2.0
  flutter_keyboard_visibility: ^4.0.2
  flutter_libphonenumber: ^0.3.11
  flutter_sim_country_code: ^0.0.3
  easy_localization: ^2.3.3+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Language
    - assets/lang/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Roboto
     fonts:
      - asset: assets/fonts/Roboto-Thin.ttf
        weight: 100
      - asset: assets/fonts/Roboto-ThinItalic.ttf
        weight: 100
        style: italic
      - asset: assets/fonts/Roboto-Light.ttf
        weight: 300
      - asset: assets/fonts/Roboto-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/Roboto-Regular.ttf
        weight: 400
      - asset: assets/fonts/Roboto-Italic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/Roboto-Medium.ttf
        weight: 500
      - asset: assets/fonts/Roboto-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Roboto-Bold.ttf
        weight: 700
      - asset: assets/fonts/Roboto-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/Roboto-Black.ttf
        weight: 900
      - asset: assets/fonts/Roboto-BlackItalic.ttf
        weight: 900
        style: italic
